### ISSUE TITLE
Dependency conflict with flutter_localizations

### ISSUE THREAD

**Issue by ghost** [GioCirque/dart-pub#1]
Because geography >=1.1.4 depends on collection ^1.16.0 and every version of flutter_localizations from sdk depends on collection 1.15.0, geography >=1.1.4 is incompatible with flutter_localizations from sdk.

**Comment by VannaDii** [comment]
I can back that down.

-Gio


On Apr 27, 2022, at 05:26, Magnus Hvidberg Wittrup ***@***.***> wrote:

﻿

Because geography >=1.1.4 depends on collection ^1.16.0 and every version of flutter_localizations from sdk depends on collection 1.15.0, geography >=1.1.4 is incompatible with flutter_localizations from sdk.

**Comment by ghost** [comment]
I have posted an issue on the main flutter repo as well, so hopefully they will fix the dependency conflict.
In the meantime, if it is possible it would be nice if you could use the collection 1.15.0 :)

**Comment by VannaDii** [comment]
Resolved by 44ae54c0cb6260d2ce3a1758f3fec080f1fa4556 and released in [geography-v1.1.5](https://github.com/GioCirque/pub-dev/releases/tag/v1.1.5-geography)
